spring:
  datasource:
    url: jdbc:mysql://localhost/mp3-register
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true