server:
  port: 8889

spring:
  application:
    name: gateway-service
  cloud:
    config:
      enabled: false
eureka:
  client:
    enabled: false

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  add-proxy-headers: true
  ignore-local-service: true
  ignoredServices: "*"
  ignoredPatterns: /api/**/internal/**
  routes:
    search:
      path: /search/**
      url: http://localhost:8788
    authorization:
       path: /register/**
       url: http://localhost:8787/register

ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 30000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

endpoints:
  restart:
    enabled: false
  shutdown:
    enabled: false
  health:
    sensitive: false
