info:
  component: Config Server
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/modestukasai/pre-configured-project-config
server:
  port: 8888
